/** Shared multiplayer protocol barrel. */

export {
  MessageType,
  RejectReason,
  MatchPhase,
  PlayerFlag,
  isMessageType,
  type HelloPayload,
  type JoinMatchPayload,
  type ClientReadyPayload,
  type InputCommandPayload,
  type PingPayload,
  type ReconnectPayload,
  type DisconnectPayload,
  type WelcomePayload,
  type RejectPayload,
  type MatchStatePayload,
  type SnapshotPlayer,
  type SnapshotProjectile,
  type SnapshotPayload,
  type PlayerJoinedPayload,
  type PlayerLeftPayload,
  type ProjectileSpawnPayload,
  type ProjectileImpactPayload,
  type DamageEventPayload,
  type DeathEventPayload,
  type RespawnEventPayload,
  type ScoreEntry,
  type ScoreUpdatePayload,
  type StandingEntry,
  type MatchEndedPayload,
  type PongPayload,
  type ServerErrorPayload,
  type EntitySpawnPayload,
  type EntityDestroyPayload,
  type LocalCorrectionPayload,
  type MessagePayloadMap,
  type ProtocolPayload,
  type DecodedMessage,
} from './messages.js'

export {
  PROTOCOL_HEADER_BYTES,
  encodeMessage,
  decodeMessage,
  validateDisplayName,
  type DecodeErrorCode,
  type DecodeError,
  type DecodeResult,
} from './codec.js'
